name: Qiita Deploy

on:
  push:
    branches:
      - main # 対象にするブランチ（必要に応じて変更してください）
    paths:
      - 'public/**' # Qiita CLIのデフォルトの記事格納ディレクトリを監視

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-size: '20' # Node.jsのバージョン

      - name: Install Qiita CLI
        run: npm install -g @qiita/qiita-cli

      - name: Deploy to Qiita
        run: qiita deploy --no-browser
        env:
          QIITA_TOKEN: ${{ secrets.QIITA_TOKEN }}
